## Review template file for MicroOS test runs on O3

Instance = "https://openqa.opensuse.org" # openQA instance to query
RabbitMQ = "amqps://opensuse:opensuse@rabbit.opensuse.org" # RabbitMQ instance to query
RabbitMQTopic = "opensuse.openqa.job.done" # RabbitMQ topic to query
HideStatus = [
  "scheduled",
  "passed",
  "softfailed",
  "cancelled",
  "skipped",
  "running",
  "uploading",
  "parallel_failed",
  "reviewed",
  "user_cancelled",
] # Hide jobs in defined states
RefreshInterval = 60 # Refresh from API once every minute
MaxJobs = 20 # Max. job per group to display
GroupBy = "groups" # Group by defined groups ("none" or "groups")
DefaultParams = { distri = "microos", version = "Tumbleweed" } # Set of default parameters
RequestJobLimit = 100 # Query up to 100 jobs per http request

## Define job groups
[[Groups]]
Name = "MicroOS Image"
Params = { flavor = "MicroOS-Image" }
MaxLifetime = 86400

[[Groups]]
Name = "MicroOS Image Container Host"
Params = { flavor = "MicroOS-Image-ContainerHost" }
MaxLifetime = 86400

[[Groups]]
Name = "MicroOS Kubic Image - kubeadm"
Params = { flavor = "MicroOS-Image-Kubic-kubeadm" }
MaxLifetime = 86400
