## Review template file for Tumbleweed test runs on O3

Instance = "https://openqa.opensuse.org" # openQA instance to query
RabbitMQ = "amqps://opensuse:opensuse@rabbit.opensuse.org" # RabbitMQ instance to query
RabbitMQTopic = "opensuse.openqa.job.done" # RabbitMQ topic to query
HideStatus = [
  "scheduled",
  "passed",
  "softfailed",
  "cancelled",
  "skipped",
  "running",
  "uploading",
  "parallel_failed",
  "reviewed",
  "user_cancelled",
] # Hide jobs in defined states
RefreshInterval = 60 # Refresh from API once every minute
MaxJobs = 20 # Max. job per group to display
GroupBy = "groups" # Group by defined groups ("none" or "groups")
RequestJobLimit = 100 # Query up to 100 jobs per http request

## Define job groups

[[Groups]]
Name = "openSUSE Slowroll"
Params = { groupid = "131" }
MaxLifetime = 86400
