---

name: openqa-mon
'on': [push, pull_request]

jobs:
  openqa-mon:
    name: openqa-mon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v6
        with: &goversion
          go-version: '1.24'
      - name: Install requirements
        run: go mod download
      - name: Build openqa-mon
        run: make openqa-mon

  openqa-mq:
    name: openqa-mq
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v6
        with: *goversion
      - name: Install requirements
        run: go mod download
      - name: Build openqa-mq
        run: make openqa-mq

  openqa-revtui:
    name: openqa-revtui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v6
        with: *goversion
      - name: Install requirements
        run: go mod download
      - name: Build openqa-review
        run: make openqa-revtui

  tomllint:
    name: "Linting _review files"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Tomllint'
        uses: uncenter/setup-taplo@v1
      - run: taplo fmt --check _review/*.toml

