---

name: openqa-mon
on: push

jobs:
  openqa-mon:
    name: openqa-mon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install requirements
        run: go mod download
      - name: Build openqa-mon
        run: make openqa-mon

  openqa-mq:
    name: openqa-mq
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install requirements
        run: go mod download
      - name: Build openqa-mq
        run: make openqa-mq

  openqa-revtui:
    name: openqa-revtui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install requirements
        run: go mod download
      - name: Build openqa-review
        run: make openqa-revtui
